# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asdfswitcher < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mikelorant/asdfswitcher/releases/download/v0.1.0/asdfswitcher_0.1.0_Darwin_arm64.tar.gz"
      sha256 "691e31ec08584257ecd09f5644d73f04ac447d07509bcc381154d28f003364b6"

      def install
        bin.install "asdfswitcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikelorant/asdfswitcher/releases/download/v0.1.0/asdfswitcher_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "6fd5f194c5ee716ae73b04c72436a874e3d2ca6a90f413abf0c4dd71413712b0"

      def install
        bin.install "asdfswitcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mikelorant/asdfswitcher/releases/download/v0.1.0/asdfswitcher_0.1.0_Linux_x86_64.tar.gz"
      sha256 "83d21ae455f0e12661940f5d0a05fac1a7b170566f9ce6991ca70af9ba456d35"

      def install
        bin.install "asdfswitcher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikelorant/asdfswitcher/releases/download/v0.1.0/asdfswitcher_0.1.0_Linux_arm64.tar.gz"
      sha256 "f6450a2252a2b54baf20a1d083e8542d04c4c03e7c7a4eb0a61229ddc9d5b176"

      def install
        bin.install "asdfswitcher"
      end
    end
  end

  depends_on "asdf"
end
