# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asdfswitcher < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mikelorant/asdfswitcher/releases/download/v0.1.0/asdfswitcher_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "075275764e2b74461361084bb6fc2a5c6dfb94e8a100358dd8e17e6a7678ad31"

      def install
        bin.install "asdfswitcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mikelorant/asdfswitcher/releases/download/v0.1.0/asdfswitcher_0.1.0_Darwin_arm64.tar.gz"
      sha256 "04516947060f809bd1a3f2a0369cdb79e5ad50ffdf3950a4022864b85773c026"

      def install
        bin.install "asdfswitcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikelorant/asdfswitcher/releases/download/v0.1.0/asdfswitcher_0.1.0_Linux_arm64.tar.gz"
      sha256 "30a5a0ad3ad34e3ea8ca7c5b97a177405030388780b494b3dabf0c28121638f0"

      def install
        bin.install "asdfswitcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikelorant/asdfswitcher/releases/download/v0.1.0/asdfswitcher_0.1.0_Linux_x86_64.tar.gz"
      sha256 "a5ed71ca904e233c7d21dc590fd755866d372faa1838a937284153d83adacfc9"

      def install
        bin.install "asdfswitcher"
      end
    end
  end

  depends_on "asdf"
end
